security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        users_in_memory: { memory: null }

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        
        main:
            lazy: true
            provider: users_in_memory

            # Correct JWT configuration
            pattern: ^/api
            stateless: true
            jwt: ~  # Це правильне налаштування для JWT

    access_control:
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }

# For testing purposes
when@test:
    security:
        encoders:
            App\Entity\User:
                algorithm: bcrypt

        providers:
            app_user_provider:
                entity:
                    class: App\Entity\User
                    property: email

        firewalls:
            api:
                pattern: ^/api
                stateless: true
                jwt: ~  # Це також налаштування для API

        access_control:
            - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }

        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
