# config/services.yaml

services:
    # Сервіс для UserService
    App\Service\UserService:
        autowire: true  # Автоматичне введення залежностей

    # Сервіс для RuntimeConstraintExceptionListener
    App\EventListener\RuntimeConstraintExceptionListener:
        tags:
            - { name: kernel.event_listener, event: kernel.exception }

    # Сервіси для Lesson Entity та пов'язаних з ним Extension та EventListener
    App\ApiPlatform\Extension\FilterLessonByNameExtension:
        tags: ['api_platform.collection_extension']

    App\ApiPlatform\Extension\PaginationLessonExtension:
        tags: ['api_platform.collection_extension']

    App\EventListener\LessonPostUpdateListener:
        tags:
            - { name: 'doctrine.event_listener', event: 'postUpdate' }

    # Default configuration for services in *this* file
    _defaults:
        autowire: true      # Автоматичне введення залежностей у ваші сервіси.
        autoconfigure: true # Автоматичне реєстрування сервісів як команди, підписники подій тощо.

    # Ресурси для класів в src/
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
